export const QASAPLOGIN = {
  txtTcode: "//span[@id='ToolbarOkCode-tr']/span/input",
  txtTcodeClick:"//span[@id='ToolbarOkCode-tr']/span",
  txtSAPUserIdds7: "//input[@id='username']",
  txtSAPPaswdds7: "//input[@id='password']",
  txtSAPUserIdqs7: "//input[@id='sap-user']",
  txtSAPPaswdqs7: "//input[@id='sap-password']",
  caOrderNumber: "//div[@id='order-number']",
  signInqs7: "//div[@id='LOGON_BUTTON']",
  va03OrderNumtxtBox: "(//form//table/tbody/tr/td[1]/input)[1]",
  va03ExecuteBtn3:"//table/tbody/tr/td/div/form/div/div[5]//span[2]/div",
  va03ExecuteBtn:"//div[@title='Execute (F8)'])",
  va03ExecuteBtn2:"//div[@title='Continue (Enter)']",
  va03z3plCheck:"(//*[text()= 'Z3PL'])[1]",
  //authCardApprovedTxt:"(//table/tbody/tr[1]/td[1]/div/div[contains(@text,'')])[11]",
  //authCardApprovedTxt:"//table//tr[1]/td[1]/div/div[9]",
  authCardApprovedTxt:"(//table//tr//tbody//div[contains(@text(),'')])[17]",
  bd87IdoctxtBox:"(//input[contains(@title,'IDoc Number')])[1]",
  bd87ExecuteBtn:"//div[@title='Execute (F8)']",
  bd87QS7txt:"(//table/tbody[1]//span/span)[43]",
  bd87IDCOReadyToProcesstxt:"(//table/tbody/tr/td[2]/div/span/span[contains(@text,'')])[6]",
  bd87CollapseNode:"(//table/tbody//span[@title='Collapse Node'])[2]",
  bd87MoreMenuOption:"(//div[@title='More'])[1]",
  bd87MoreMenuProcessOption:"(//span[text()='Process'])",
  bd87Successtxt:"//table/tbody/tr/td[2]/div/span[contains(@text,'')]",
  bd87idocStatus53:"(//table/tbody/tr/td/div/form//span)[126]",
  bd87DirectProcessBtn:"//*[contains(@title,'Process Selected Node')]",
  va03WebsiteOrderTxt:"//input[contains(@title,'Sales Document')]",
  va03DisplayDocumentBtn:"//table/tbody/tr/td/div/form//span[4]/div[contains(@title,'Display')]",
  programFindbtn:"//*[contains(@id,'ls-inputfieldhelpbutton')]",
  programFindclose:"//*[@title='Close']",
  authExecuteBtn1:"//*[contains(@lsdata,'Execute (F8)')]",
  txtProgram:"//*[@name='InputField']",
  authPDFTxt:"//span[contains(@title,'PDF')]",
  //authOrdertype:"//*[@id='M0:46:::1:34']",
  prgmNameTxtbox:"//input[@title='ABAP Program Name']",
  authExecuteBtn2:"//*[contains(@title,'F8')]",
  authOrderno:"(//input[contains(@title,'Sales Document')])[3]",
  authSuccessMsg:"//*[contains(@lsdata,'successfully')]",
  authSuccessTick:"//*[contains(@lsdata,'Continue (Enter)')]",
  authSuccClose:"//button[contains(@title,'Close')]",
  authExecuteBtn4:"//table/tbody/tr/td/div/form/div/div[5]/div/div/div[1]/span[2]/div",
  idocnum:"//table/tbody/tr/td/div/form/div/div[5]/div/div/div[1]/div/span[3]",
  //authExecuteBtn2:"//*[contains(@class,'lsButton lsButton--base urNoUserSelect urBtnRadius lsButton--useintoolbar lsButton--active lsButton--focusable lsButton--up lsButton--design-emphasized')]",
  poSalesDocNo:"//*[@title='Sales and Distribution Document Number']",
  authPageTxtBox:"//input[@name='InputField']",
  GIgenerated: "//*[contains(text(),'GI')]//parent::span/parent::div/parent::td//parent::tr//td[1]",
  va03DisplayDocPONum:"(//table/tbody/tr/td[2]/div/span/span[contains(@text,'')])[1]",
  va03PONUM:"//table/tbody/tr[3]/td/div/div/table/tbody[1]/tr[2]/td[2]/div/div/table/tbody/tr/td[1]/div/span",
  va03PODisplyDoc:"//div[contains(@title,'Display')]",
  va03DIntNum:"(//table/tbody[1]/tr[2]/td[1]/div/div/table/tbody/tr[1]/td[3]//span/span[contains(@name,'InputField')])[2]",
  //va03DIntNum:"(//table/tbody[1]/tr[2]/td[1]/div/div/table/tbody/tr[1]/td[3]//span/span[contains(@text,'')])[2]"
  va03arrow:"//table/tbody/tr/td/div/form/div/div[4]/div/div[1]/div/div[4]/div/div[2]/div/div/div/div[2]/div/div/table/tbody/tr[1]/td/table/tbody/tr/td[3]/span[1]",
  va03ItemDetailsExpand:"//div[contains(@title,'Expand Item Details Ctrl+F4')]",
//va03PohistoryTab:"//div[8]/div[contains(@class,'lsTabStrip--item-title')]",
  va03PohistoryTab:"(//div[8]/div[contains(@text,'')])[1]",
  va03PickTab:"//table/tbody/tr/td/div/form//table/tbody/tr[1]/td/table/tbody/tr/td[2]/div/div[2]",
  //va03PickTabItem10Checkbx:"((//table)//tbody/tr[1]/td[1]/div/div)[6]",
  va03ChangeMode:"//div[contains(@title,'Display <-> Change (Ctrl+F1)')]",
  va03DelQty:"(//table/tbody/tr[1]/td[2]/div/span/span)[2]",
  //va03PickQty:"//table/tbody/tr[1]/td[5]/div/span/span",
  va03PickSaveBtn:"//div[contains(@title,'Save')]",
  va03PickQtyClick:"(//table/tbody/tr[1]/td[5]/div/span/span[contains(@ti,'')]/..)[1]",
  va03PickQty:"(//table/tbody/tr[1]/td[5]/div/span/span[contains(@ti,'')]/..//input)[1]",
  va03CollapseBtnItemOverview:"//div[contains(@title,'Collapse Items Ctrl+F6')]",
  va03PickTabItem10Checkbx:"((//table)//tbody/tr[1]/td[1]/div)[18]",
  replinishDelMenu:"//div[contains(@title,'Menu')]",
  releaseMenuJob: "(//table/tbody/tr[contains(@title,'Job')])[1]",
  releaseMenuReleaseScheduled: "(//table/tbody/tr[contains(@title,'Released -> Scheduled')])[1]",
  releasebtn: "//div[contains(@title, 'Release job (Ctrl+Shift+F10)')]",
  immediateReleasebtn: "//*[contains(@lsdata,'Immediate')]",
  releaseSave: "//*[contains(@lsdata,'Save')]",
  replinishDelMenuExtras:"//table/tbody/tr[contains(@title,'Extras')]",
  replinishDelDeliveryOuput:"//table/tbody/tr[contains(@title,'Delivery Output')]",
  replinishHeader:"//table//tbody/tr/td/div/div/div[1]/div[2]/span[10]//div//table/tbody//tr[contains(@title,'Header')]",
  zescOutputStatus:"//span[contains(@title,'Not processed')]",
  zescOutStatus2:"//span[contains(@title,'Successfully processed')]",
  //va03DIntNumForGr:"(//table/tbody/tr[1]/td[3]/div/span/span)[1]",
  //va03DIntNumForGr:"//table/tbody[1]/tr[2]/td[1]/div/div/table/tbody/tr[3]/td[3]/div/span",
  va03DIntNumForGr:"//*[contains(text(),'DlNt')]//parent::span/parent::div/parent::td//parent::tr//td[3]",
  va03backBtn:"//div[contains(@title,'Back')]",
  //va03OBDNum:"//input[contains(@title,'Delivery')]"
  va03OBDNum:"//table/tbody/tr/td/div/form/div/div[4]/div/div[1]/span/span/span[contains(@text,'')]",
  purOrdTab:"//*[contains(@tabindex,'-1') and contains(text(),'Purchase Orders')]",
  purOrdNoInPOTab:"//tbody[contains(@aria-label,'Add. Criteria - Stock Transport Order')]/tr[2]/td/table/tbody/tr/td/div/div/div/div[2]/table/tbody/tr/td[1]/input",
  purOrdHistTab:"//*[contains(text(),'Purchase Order History') and contains(@id,'title')]",
  dintVer:"//*[contains(text(),'DlNt')]",
  execute:"//div[@title='Execute (F8)']",
  bbDeliveryType:"//input[@title='Delivery Type']",
  bbDeliveryNo:"//table/tbody/tr/td/div/div/div/div[22]/table/tbody/tr/td/input",
  bbCheckbox:"//*[contains(@name,'CheckBox')]",
  rsnastOutputType:"(//input[contains(@title,'Application for output conditions')])[1]",
  rsnastObjectKey:"(//input[contains(@title,'Object key')])[1]",
  rsnastZESCOutputType:"(//input[contains(@title,'Output Type')])[1]",
  rsnastExecuteBtn:"(//div[contains(@title,'Execute ' )])[2]",
  rsnastLoading1:"//div[contains(@title,'Loading')]",
  rsnastLoading2:"//div[contains(@title,'More')]",
  rsnastSuccessPopupContinueBtn:"//div[contains(@title,'Continue')]",
  va03ODB:"//*[contains(text(),'Outbound D')]",
 //f2 invoice
 salesOrg: "//*[@title='Sales Organization']",
 sdDocument: "//*[@title='From document']",
 salesOrderchkBx: "//*[@aria-label='Sales orders']",
 deliverieschkBx: "//*[@aria-label='Deliveries']",
 jobName: "//*[@title='Background job name']",
 schedChkBx: "//*[@aria-label='Sched.']",
 invoiceDoc: "/html/body/table/tbody/tr/td/div/form/div/div[4]/div/div[1]/div/table/tbody/tr[3]/td/div/div/div/div/div[2]/div/div/table/tbody[1]/tr[2]/td[1]/div/div[2]/table/tbody/tr[7]/td/table/tbody/tr/td[3]/div/table/tbody/tr/td[2]/div/span/span",
 changeBtn: "//*[@title='Change (Ctrl+F11)']",
 billingDateTxt: "//*[@title='Billing Date']",
 billingDatebtn: "//*[@id='ls-inputfieldhelpbutton']",
 CalenderContinue: "//*[@title='Continue (Enter)']",
 odbPGISuccesstxt:"//div[contains(@title,'successful')]",
 saveBtn: "//*[@title='Save (Ctrl+S)']",
 companyCode: "//*[@title='Company Code']",
 displayHeaderDetails: "//*[@title='Display header details']",
 currentDatePicker: "//*[@class = 'urTodayI urBorderBox lsCalItemText']",
 jobNameInvoice: "//*[@title='Job name']",
 JobInvoiceName: "//div[@role='text' and contains(@style, 'top:81px')]",
 authOrdertype:"//*[@title='Sales Document Type']",
  JobName:"//div[contains(text(),'INVOICE')]",
 //authExecuteBtn2:"//*[contains(@class,'lsButton lsButton--base urNoUserSelect urBtnRadius lsButton--useintoolbar lsButton--active lsButton--focusable lsButton--up lsButton--design-emphasized')]",

 PurchaseOrderDoc: "/html/body/table/tbody/tr/td/div/form/div/div[4]/div/div[1]/div/table/tbody/tr[3]/td/div/div/div/div/div[2]/div/div/table/tbody[1]/tr[2]/td[1]/div/div[2]/table/tbody/tr[2]/td/table/tbody/tr/td[3]/div/table/tbody/tr/td[2]/div/span/span",
 obdDocument: "/html/body/table/tbody/tr/td/div/form/div/div[4]/div/div[1]/div/table/tbody/tr[3]/td/div/div/div/div/div[2]/div/div/table/tbody[1]/tr[2]/td[1]/div/div[2]/table/tbody/tr[3]/td/table/tbody/tr/td[3]/div/table/tbody/tr/td[2]/div/span/span",
 obdDocumentStatus: "/html/body/table/tbody/tr/td/div/form/div/div[4]/div/div[1]/div/table/tbody/tr[3]/td/div/div/div/div/div[2]/div/div/table/tbody[1]/tr[2]/td[2]/div/div[2]/table/tbody/tr[3]/td[3]/div/span/span/span",
 displayDocumentBtn: "//*[@title='Display Document (F8)']",
 dintNo: "//span[@maxlength='10']",
 pickingTab: "//div[@aria-selected='false']",
 displayChangeModeBtn: "//*[@title='Display <-> Change (Ctrl+F1)']",
 postGoodsIssue: "//*[@title='Post Goods Issue (Shift+F8)']",
 salesDocExecuteBtn: "//*[@class='lsButton lsButton--base urNoUserSelect urBtnRadius lsButton--useintoolbar lsButton--active lsButton--focusable lsButton--up lsButton--behaviour-toggle lsButton--design-standard']",
 sa38ExecuteBtn: "//*[@title='Execute (F8)']",
 bbItemdoubleClick:"//table/tbody/tr[1]/td[2]/div/span/span[1]",
 bbItemdoubleClick2:"//table/tbody/tr[1]/td[2]/div/span/span[2]",
 va03NextItem:"//div[contains(@title,'Next Item')]",
 rsnastSuccMsg:"//div[contains(@title,'Message text')]",
 rsnastInfoScreen:"//span[contains(@id,'SAPMSDYP10_1-header-title-txt')]",
  bbBillingPlan:"//div/*[contains(text(),'Billing plan')]",
  bbBlock:"//table/tbody/tr[1]/td[6]/div/span/span",
  bbBlock2:"//table/tbody/tr[2]/td[6]/div/span/span",
  migoPO:"//*[(@title='Purchase Order')]",
  migoSite:"//*[(@title='Ordering Site')]",
  gr101:"//tbody[1]/tr[2]/td[1]/div/div/table/tbody/tr[1]/td[2]/div/span/span[contains(text(),'101')]",
  deliveryCode: "//*[@title='Delivery']",
  bkButton:"//*[contains(@title,'Back (F3)')]",
  deliverychkbx: "//div[@ct='ALC' and @role='checkbox']",
  postGoodsIssueOnOBDPage: "//*[@title='Post Goods Issue (F8)']",
  GICOMStockDoc: "(//table/tbody/tr/td[2]/div/span/span[contains(@text,'')])[5]",
  jobStatus: "/html/body/table/tbody/tr/td/div/form/div/div[4]/table/tbody/tr[1]/td[1]/div/div[162]",
  journalStatus: "//span[@role='button' and @tabindex='0' and text()='Cleared']",
  appliancePODoc: "(//table/tbody/tr/td[2]/div/span/span[contains(@text,'')])[2]",
  JobNametext: "//*[@title='Background job name']",
  checkbxClicked: "//span[@class='lsAbapListCheckBox lsAbapListCheckBox--hoverable']",

 };

